### ISSUE TITLE
App's name

### ISSUE THREAD

**Issue by skycommand** [zodiacon/TotalRegistry#25]
Hello.

Are you aware that there are other apps called "Registry Explorer"?

A particularly mature app with this name is [Eric Zimmerman's Registry Explorer](https://ericzimmerman.github.io/#!index.md), which bears the same app icon. Right now, it's at version 1.6.0.0.

The other is an old one at regxplor.com.

**Comment by zodiacon** [comment]
I wasn't aware. It just seemed like a good name.

**Comment by unforgettableid** [comment]
Dear @zodiacon:

If you do a Google search for [ [`download Registry Explorer`](https://www.google.com/search?q=download+Registry+Explorer) ], @EricZimmerman's tool comes up first.

If you do a search on YouTube for [ [`Registry Explorer`](https://www.youtube.com/results?search_query=Registry+Explorer) ], you'll find multiple videos about Eric's tool.

If you use the Chocolatey package manager, and you enter the command `chocolatey install registryexplorer`, it will automatically download and install Eric's tool for you.

You don't have to rename your tool, but it's up to you.

I think it would probably be best to rename your tool.  This might help to avoid confusion.  It would also avoid the future risk of name collisions for users who use Chocolatey and/or WinGet (the Windows Package Manager, which is included with Windows 10 and higher).

If you're planning to ever rename Registry Explorer:  The sooner you do it, the easier it will be.  As more articles and third parties write and talk about it, and upload it to software-distribution websites, it becomes harder to rename it, since the articles and/or websites may continue to refer to the old name.

Here are some suggested alternative names for Registry Explorer:

Registry King
Registry Boss
Registry Man
Registry Champ
Registry Mogul
Registry Dude
Registry Pal
Registry Friend

The names "OpenRegistry" and "Registry Buddy" seem to already be taken.

@zodiacon, do you like any of my suggested names?

**Comment by zodiacon** [comment]
OK, fine... I will rename.
How about TotalRegistry?

**Comment by zodiacon** [comment]
Yeah, I think I'll go with Total Registry.
